/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutInterests: typeof import('./components/aboutMe/AboutInterests.vue')['default']
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BetweenPage: typeof import('./components/BetweenPage.vue')['default']
    CardPreset: typeof import('./components/aboutMe/interestCards/CardPreset.vue')['default']
    CatergorizedCards: typeof import('./components/aboutMe/interestCards/CatergorizedCards.vue')['default']
    Certs: typeof import('./components/Certs.vue')['default']
    EnglishHerosJourney: typeof import('./components/projects/EnglishHerosJourney.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    GameServers: typeof import('./components/projects/GameServers.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    MusicalFeats: typeof import('./components/aboutMe/MusicalFeats.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Portfolio: typeof import('./components/Portfolio.vue')['default']
    PrevalentSkills: typeof import('./components/aboutMe/PrevalentSkills.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    ReactAboutMe: typeof import('./components/projects/ReactAboutMe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./components/aboutMe/skills/Skill.vue')['default']
    Snake: typeof import('./components/projects/Snake.vue')['default']
    SportFeats: typeof import('./components/aboutMe/SportFeats.vue')['default']
  }
}
