/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutInterests: typeof import('./components/aboutMe/AboutInterests.vue')['default']
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BetweenPage: typeof import('./components/BetweenPage.vue')['default']
    CardPreset: typeof import('./components/aboutMe/cards/CardPreset.vue')['default']
    CatergorizedCards: typeof import('./components/aboutMe/cards/CatergorizedCards.vue')['default']
    Certs: typeof import('./components/Certs.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NotesAboutMe: typeof import('./components/aboutMe/NotesAboutMe.vue')['default']
    Portfolio: typeof import('./components/Portfolio.vue')['default']
    PrevalentSkills: typeof import('./components/aboutMe/PrevalentSkills.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./components/aboutMe/skills/Skill.vue')['default']
    Snake: typeof import('./components/projects/Snake.vue')['default']
  }
}
